//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adId { get; set; }
        public string adminEmail { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Contact { get; set; }
        public string Password { get; set; }
        public Nullable<int> suppId { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> drvId { get; set; }
    }
}
