//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentId { get; set; }
        public string cardName { get; set; }
        public string cardCCV { get; set; }
        public string cardType { get; set; }
        public string cardExpMonth { get; set; }
        public string cardExpYear { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> custId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
