//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int suppId { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string quantity { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual supplierinfo supplierinfo { get; set; }
    }
}
