//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriver
    {
        public int drvId { get; set; }
        public string drvFirstname { get; set; }
        public string drvLastname { get; set; }
        public string drvContact { get; set; }
        public string drvEmail { get; set; }
        public string drv_Password { get; set; }
        public Nullable<int> orderId { get; set; }
    }
}
